
.PHONY: all release clean

all:
	$(MAKE) -C libpsplink all
	$(MAKE) -C libpsplink_driver all
	$(MAKE) -C libusbhostfs all
	$(MAKE) -C libusbhostfs_driver all
	$(MAKE) -C psplink all PSP_FW_VERSION=271
	$(MAKE) -C psplink_user all PSP_FW_VERSION=271
	$(MAKE) -C usbhostfs all PSP_FW_VERSION=271
	$(MAKE) -C usbgdb all PSP_FW_VERSION=271
	$(MAKE) -C bootstrap release PSP_FW_VERSION=271

release: clean all
	mkdir -p release/
	mkdir -p release/pc
	mkdir -p release/psplink
	cp -Rf scripts release/scripts
	cp psplink/psplink.prx release/psplink
	cp psplink/psplink.ini release/psplink
	cp psplink_user/psplink_user.prx release/psplink
	cp usbhostfs/usbhostfs.prx release/psplink
	cp usbgdb/usbgdb.prx release/psplink
	cp bootstrap/EBOOT.PBP release/psplink
	cp -Rf pspsh release/pc
	mkdir release/pc/psplink
	cp psplink/shellcmd.h release/pc/psplink
	cp -Rf usbhostfs_pc release/pc
	cp usbhostfs/usbhostfs.h release/pc/usbhostfs_pc
	cp README.md release
	cp LICENSE release
	cp psplink_manual.pdf release

clean:
	$(MAKE) -C libpsplink clean
	$(MAKE) -C libpsplink_driver clean
	$(MAKE) -C libusbhostfs clean
	$(MAKE) -C libusbhostfs_driver clean
	$(MAKE) -C psplink clean
	$(MAKE) -C psplink_user clean
	$(MAKE) -C usbhostfs clean
	$(MAKE) -C usbgdb clean
	$(MAKE) -C bootstrap clean
	rm -rf release
